# Generated by Django 4.2.7 on 2025-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_App', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.FileField(null=True, upload_to='static\\Company_Profiles'),
        ),
    ]
